/**
 * \kernelgroup{SceSysmem}
 * \usage{psp2common/kernel/sysmem.h}
 */

#ifndef _PSP2COMMON_KERNEL_SYSMEM_H_
#define _PSP2COMMON_KERNEL_SYSMEM_H_

#include <vitasdk/build_utils.h>
#include <psp2common/types.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef SceUInt32 SceKernelMemBlockType;
VITASDK_BUILD_ASSERT_EQ(4, SceKernelMemBlockType);

typedef enum SceKernelMemoryType {
	SCE_KERNEL_MEMORY_TYPE_NORMAL_NC = 0x80, //!< Non-cached memory type
	SCE_KERNEL_MEMORY_TYPE_NORMAL    = 0xD0  //!< Cached memory type
} SceKernelMemoryType;

typedef struct SceKernelMemBlockInfo {
	SceSize size;
	void *mappedBase;
	SceSize mappedSize;
	int memoryType; //!< One of ::SceKernelMemoryType
	SceUInt32 access;
	SceKernelMemBlockType type;
} SceKernelMemBlockInfo;
VITASDK_BUILD_ASSERT_EQ(0x18, SceKernelMemBlockInfo);

/*
 * User/Kernel shared memtypes
 */

#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_L1WBWA_RW    (0x09404060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_R            (0x09408040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_RW           (0x09408060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_DEVICE_RW     (0x0C200860)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_R             (0x0C20D040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_RW            (0x0C20D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_NC_RW         (0x0C208060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_GAME_RW       (0x0C50D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_PHYCONT_RW    (0x0C80D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_PHYCONT_NC_RW (0x0D808060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_CDIALOG_RW    (0x0CA0D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_CDIALOG_NC_RW (0x0CA08060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_TOOL_RW       (0x0CF0D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_TOOL_NC_RW    (0x0CF08060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_R          (0x0E20D040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_RW         (0x0E20D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_NC_R       (0x0E208040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_NC_RW      (0x0E208060)


/*
 * For Backwards compatibility
 */

#define SCE_KERNEL_MEMBLOCK_TYPE_USER_RW_UNCACHE         (0x0C208060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_RW                 (0x0C20D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_TOOL_NC_RW         (0x0CF08060)


typedef enum SceKernelAllocMemBlockAttr {
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_VBASE        = 0x00000001U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PBASE        = 0x00000002U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_ALIGNMENT    = 0x00000004U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_EXTRA_LOW    = 0x00000008U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_EXTRA_HIGH   = 0x00000010U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_OPEN_RESTRICTIONS = 0x00000020U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_BASE         = 0x00000040U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PID          = 0x00000080U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_BASENAME     = 0x00000200U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PPAV         = 0x00001000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_ROUNDUP      = 0x00002000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_ENABLE_OPEN      = 0x00004000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_DOMAIN       = 0x00010000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_NOPHYPAGE        = 0x00020000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_DONT_MAP         = 0x00040000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_PHYCONT          = 0x00200000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_SKIP_ZERO_FILL   = 0x00400000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_SHARE_VBASE      = 0x00800000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_SHARE_PHYPAGE    = 0x01000000U,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_ALLOW_PARTIAL_OP = 0x04000000U,

	/* Compatibility aliases for the names previously exposed by VitaSDK. */
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_0x20          = SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_OPEN_RESTRICTIONS,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_0x4000        = SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_ENABLE_OPEN,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PADDR          = SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PBASE,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_MIRROR_BLOCKID = SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_BASE,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PADDR_LIST     = SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_HAS_PPAV,
	SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_UNK                = SCE_KERNEL_ALLOC_MEMBLOCK_ATTR_SKIP_ZERO_FILL
} SceKernelAllocMemBlockAttr;

typedef enum SceKernelModel {
	SCE_KERNEL_MODEL_VITA   = 0x10000,
	SCE_KERNEL_MODEL_VITATV = 0x20000
} SceKernelModel;


#ifdef __cplusplus
}
#endif

#endif /* _PSP2COMMON_KERNEL_SYSMEM_H_ */
