/**
 * \kernelgroup{SceSysmem}
 * \usage{psp2common/kernel/sysmem.h}
 */

#ifndef _PSP2COMMON_KERNEL_SYSMEM_H_
#define _PSP2COMMON_KERNEL_SYSMEM_H_

#include <psp2common/types.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef SceUInt32 SceKernelMemBlockType;

/*
 * User/Kernel shared memtypes
 */

#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_L1WBWA_RW    (0x09404060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_R            (0x09408040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_RW           (0x09408060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_DEVICE_RW     (0x0C200860)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_R             (0x0C20D040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_RW            (0x0C20D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_NC_RW         (0x0C208060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_GAME_RW       (0x0C50D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_PHYCONT_RW    (0x0C80D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_PHYCONT_NC_RW (0x0D808060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_CDIALOG_RW    (0x0CA0D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_CDIALOG_NC_RW (0x0CA08060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_TOOL_RW       (0x0CF0D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_TOOL_NC_RW    (0x0CF08060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_R          (0x0E20D040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_RW         (0x0E20D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_NC_R       (0x0E208040)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_CDIALOG_NC_RW      (0x0E208060)


/*
 * For Backwards compatibility
 */

#define SCE_KERNEL_MEMBLOCK_TYPE_USER_RW_UNCACHE         (0x0C208060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_RW                 (0x0C20D060)
#define SCE_KERNEL_MEMBLOCK_TYPE_USER_TOOL_NC_RW         (0x0CF08060)



#ifdef __cplusplus
}
#endif

#endif /* _PSP2COMMON_KERNEL_SYSMEM_H_ */
