var group__kernel =
[
    [ "C Standard Library", "group__SceCLib.html", "group__SceCLib" ],
    [ "CPU Library", "group__SceCPU.html", "group__SceCPU" ],
    [ "System Module Library", "group__SceSysmodule.html", "group__SceSysmodule" ],
    [ "Kernel Errors", "group__SceKernelError.html", "group__SceKernelError" ],
    [ "Loadcore Library", "group__SceLoadcore.html", "group__SceLoadcore" ],
    [ "Module Manager Library", "group__SceModulemgr.html", "group__SceModulemgr" ],
    [ "Process Manager Library", "group__SceProcessmgr.html", "group__SceProcessmgr" ],
    [ "Thread Manager Library", "group__SceThreadMgr.html", "group__SceThreadMgr" ],
    [ "System Memory Library", "group__SceSysmem.html", "group__SceSysmem" ],
    [ "Direct Memory Access Controller", "group__SceDmacMgr.html", "group__SceDmacMgr" ],
    [ "OpenPsid Library", "group__SceOpenPsid.html", "group__SceOpenPsid" ],
    [ "Random Number Library", "group__SceRng.html", "group__SceRng" ],
    [ "Suspend Library", "group__SceSuspend.html", "group__SceSuspend" ],
    [ "Interrupt Manager Library", "group__SceIntrMgr.html", "group__SceIntrMgr" ],
    [ "Exception handling Library", "group__SceExcpmgr.html", "group__SceExcpmgr" ],
    [ "utils Library", "group__SceUtils.html", "group__SceUtils" ],
    [ "IdStorage Library", "group__SceIdStorage.html", "group__SceIdStorage" ],
    [ "Process event Library", "group__SceProcEvent.html", "group__SceProcEvent" ],
    [ "Kernel system root Library", "group__SceKernelSysroot.html", "group__SceKernelSysroot" ],
    [ "Kernel C Library", "group__SceSysclib.html", "group__SceSysclib" ],
    [ "Kernel Ss Library", "group__SceSblSsMgr.html", "group__SceSblSsMgr" ],
    [ "dip switch Library", "group__SceDipsw.html", "group__SceDipsw" ]
];