var searchData=
[
  ['kernel',['Kernel',['../group__kernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceBtKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceCPUKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceCtrlKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceDevCtlKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceDirEntKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceDisplayKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceFcntlKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceGpioKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceIntrMgrKernel.html',1,'']]],
  ['kernel_20errors',['Kernel Errors',['../group__SceKernelError.html',1,'']]],
  ['kernel',['Kernel',['../group__SceModulemgrKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceNetKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceProcessmgrKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceSblACMgrKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceSblAuthMgrKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceStatKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceSuspendKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceSysmemKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceThreadMgrKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceTypesKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceUdcdKernel.html',1,'']]],
  ['kernel',['Kernel',['../group__SceUsbSerialKernel.html',1,'']]]
];
