name: Check

on:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types: [run_build]

env:
  VITASDK: /usr/local/vitasdk

jobs:
  check-headers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/checkout@v6
      with:
        repository: vitasdk/vdpm
        path: vdpm
    - name: Install vitasdk
      run: |
        bash vdpm/bootstrap-vitasdk.sh
        echo "$VITASDK/bin" >> "$GITHUB_PATH"
    - name: Install packages
      run: vdpm SDL2 curl openssl soloud taihen zlib zstd
    - name: Check
      run: |
        set -e
        export TRAVIS_BUILD_DIR=$PWD
        cd $TRAVIS_BUILD_DIR
        export INCLUDE_DIR=$TRAVIS_BUILD_DIR/include
        ls ./db | xargs -I__name__ vita-nid-check -dbdirver=./db/__name__ -dbg=trace
        # Make sure headers are valid
        # bash $TRAVIS_BUILD_DIR/.travis.d/download_external_libs.sh
        cd $VITASDK/arm-vita-eabi/include
        rm -rf psp2 psp2common psp2kern vitasdk vitasdk.h vitasdkkern.h
        cd $TRAVIS_BUILD_DIR
        find $INCLUDE_DIR -type f -name "*.h" | xargs -I FN -n 1 -P 4 arm-vita-eabi-gcc -I$INCLUDE_DIR -fsyntax-only -c FN -o /dev/null
        find $INCLUDE_DIR -type f -name "*.h" | xargs -I FN -n 1 -P 4 arm-vita-eabi-g++ -I$INCLUDE_DIR -fsyntax-only -c FN -o /dev/null
        cd $VITASDK/arm-vita-eabi/lib
        rm -rf *libSce*_stub.a
        cd $TRAVIS_BUILD_DIR
        cp -r include/* $VITASDK/arm-vita-eabi/include
        # header define check
        BYPASS_VITA_LIBS_GEN=1 USE_LINT=1 python3 build.py output
    - name: DB Stub test
      run: |
        vita-libs-gen-2 -yml=./db -output=./stubs
        cd ./stubs
        make -j$(nproc) install
        cd ..
        rm stubs/makefile
        tar "cfvj" "vitasdk-db-stubs.tar.bz2" "stubs"
    - name: Header sanitize checks
      run: |
        python3 ./includes_all.py ../include
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
        cmake --build build
      working-directory: check_size
    - name: NID compat checks
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
        cmake --build build
      working-directory: check_nid_compat
    - uses: actions/checkout@v6
      with:
        repository: vitasdk/samples
        path: samples
    - name: Sample build test
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
        cmake --build build
      working-directory: samples
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v6
      with:
        name: vitasdk-db-stubs
        path: vitasdk-db-stubs.tar.bz2
